apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
    - --dockerfile=/opt/flask-demo/Dockerfile
    - --context=/opt/flask-demo
    - --destination=fc277073030/flask-demo:v1
    volumeMounts:
      - name: context-data
        mountPath: /opt/flask-demo
      - name: docker-config
        mountPath: /kaniko/.docker/
  restartPolicy: Never
  volumes:
    - name: context-data
      hostPath:
        path: /Users/fanchao/PycharmProjects/flask-demo
        type: Directory
    - name: docker-config
      configMap:
        name: docker-config
